### PR TITLE
fix(class): property visibility checks #375

### LINKED ISSUE #375: Visibility not respected in `read_property` and `write_property`
This allows private properties to be read and writable or readonly properties to be writeable from php.

### PR DESCRIPTION
**Pull request by kakserpom**
Fixes #375

### CODE REVIEW

**Comment by kakserpom** [comment]
> LGTM. Could you remove the unrelated docblock changes from this PR?

rustfmt did that. Is that a problem?

**Comment by Xenira** [comment]
> rustfmt did that. Is that a problem?

Just to make history cleaner and prevent conflicts. Not a big thing, and usually fine. Just saw a lot of those changes in your PRs and in that case its better to do one PR containing all rustfmt changes.

File: src/types/zval.rs [hunk 1]
```diff
@@ -709,14 +709,7 @@ impl Zval {
...
     pub fn set_hashtable(&mut self, val: ZBox<ZendHashTable>) {
-        // Handle immutable shared arrays (e.g., the empty array) similar to
-        // ZVAL_EMPTY_ARRAY. Immutable arrays should not be reference counted.
-        let type_info = if val.is_immutable() {
-            ZvalTypeFlags::Array
-        } else {
-            ZvalTypeFlags::ArrayEx
-        };
-        self.change_type(type_info);
+        self.change_type(ZvalTypeFlags::ArrayEx);
```
Comment (Xenira) [inline src/types/zval.rs]: This reverts #631

**Review by Xenira — CHANGES_REQUESTED** [review]

**Review by Xenira — APPROVED** [review]
