### PR TITLE
fix(macro): reference mutability inside Option #515

### LINKED ISSUE #515: Argument #1 ($foo) could not be passed by reference
```
use ext_php_rs::types::ZendHashTable;
use ext_php_rs::prelude::*;

#[php_class]
pub struct Example {}

#[php_impl]
impl Example {
    fn __construct() -> Self {
        Self {}
    }
    pub fn foo(&self, foo: Option<&ZendHashTable>) {}
}

#[php_module]
pub fn get_module(module: ModuleBuilder) -> ModuleBuilder {
    module.class::<Example>()
}
```

```
<?php
$example = new Example;
$example->foo([1,2,3]);
echo $bar;
```

Note that it works without `Option<...>`.

This works too:
```
$foo = [1,2,3];
$example->foo($foo);
```

### PR DESCRIPTION
**Pull request by kakserpom**
Fixes #515

### CODE REVIEW

**Comment by ptondereau** [comment]
~bugfix(macro): reference mutability inside Option~
fix(macro): reference mutability inside Option

File: tests/src/integration/array/mod.rs [hunk 1]
```diff
@@ -41,13 +41,20 @@ pub fn test_array_keys() -> Zval {
     ht.into_zval(false).unwrap()
 }
 
+/// Test that `Option<&ZendHashTable>` can accept literal arrays (issue #515)
+#[php_function]
+pub fn test_optional_array_ref(arr: Option<&ZendHashTable>) -> i64 {
```
Comment (ptondereau) [inline tests/src/integration/array/mod.rs:46]: can we also add a test with `arr: Option<&mut ZendHashTable>`? It would add an anti regression test for mutable param
