### PR TITLE
fix(zval): Heap corruption with persistent=true #424

### LINKED ISSUE #424: Core dumped where try Zval::set_string with persist trye
```rust
use ext_php_rs::prelude::*;
use ext_php_rs::types::Zval;

pub fn startup(_ty: i32, _: i32) -> i32 {
    0
}

#[php_class]
#[derive(Default)]
struct Test {}

#[php_impl]
impl Test {
    #[php(constructor)]
    fn __constructor() -> Self {
        Self {}
    }
    fn test(&self) {
        let mut z = Zval::new();
        let _ = z.set_string("TEST", true);
    }
}

#[php_module]
fn module(module: ModuleBuilder) -> ModuleBuilder {
    module.class::<Test>()
}
```

```php
<?php

$t = new Test;

var_dump($t->test());
```

Output
```bash
zend_mm_heap corrupted
[2]    41472 IOT instruction (core dumped)  php -d extension=./target/debug/libtest_php_ext.so ./index.php
```

OS: Archlinux

### PR DESCRIPTION
**Pull request by kakserpom**
Fixes #424

### CODE REVIEW

File: tests/src/integration/persistent_string/mod.rs [hunk 1]
```diff
@@ -0,0 +1,79 @@
+//! Integration tests for issue #424 - `Zval::set_string` with persistent flag
+//!
+//! Tests that persistent strings are correctly handled when a Zval is dropped.
```
Comment (ptondereau) [inline tests/src/integration/persistent_string/mod.rs]:
```suggestion
```

I think this useless

File: tests/src/integration/persistent_string/mod.rs [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+
+use ext_php_rs::prelude::*;
+use ext_php_rs::types::Zval;
+
+/// Test persistent string creation and drop
```
Comment (ptondereau) [inline tests/src/integration/persistent_string/mod.rs]: All these comments before the test function are useless because the function name should reflect the test case.

File: tests/src/integration/persistent_string/persistent_string.php [hunk 3]
```diff
@@ -0,0 +1,34 @@
+<?php
+
+/**
+ * Integration test for issue #424 - Zval::set_string with persistent flag
+ *
+ * Tests that persistent strings are correctly handled when a Zval is dropped,
+ * without causing heap corruption.
+ */
```
Comment (ptondereau) [inline tests/src/integration/persistent_string/persistent_string.php]: same here, we know what we're doing by the name of the file

File: tests/src/integration/persistent_string/persistent_string.php [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+
+// Test 5: Interned string (persistent)
+$result = test_interned_string_persistent();
+assert($result === "interned persistent test passed", "Interned persistent string test failed: $result");
+
+// Test 6: Interned string (non-persistent)
+$result = test_interned_string_non_persistent();
+assert($result === "interned non-persistent test passed", "Interned non-persistent string test failed: $result");
+
+echo "All persistent string tests passed!\n";
```
Comment (ptondereau) [inline tests/src/integration/persistent_string/persistent_string.php]: Useless as all assertions are the guards

**Comment by kakserpom** [comment]
@ptondereau Done
