### PR TITLE
fix(macro): identifier-related bugs #536

### LINKED ISSUE #536: macros: raw identifier bug
Branch: master

```
use ext_php_rs::prelude::*;

#[php_class]
pub struct Example {}
#[php_impl]
impl Example {
    pub fn foo(&self, r#as: &str) {}
}
#[php_module]
pub fn get_module(module: ModuleBuilder) -> ModuleBuilder {
    module.class::<Example>()
}
```

```
<?php

// Stubs for untitled5

namespace {
    class Example {
        public function foo(string $r#as) {}

        public function __construct() {}
    }
}
```

Also, `__construct()` in stubs is unnecessary since you can't instantiate this class from PHP.

P.S. Pardon me for not using the issue templates :-)

### PR DESCRIPTION
**Pull request by kakserpom**
Fixes #536

### CODE REVIEW

File: crates/macros/src/parsing.rs [hunk 1]
```diff
@@ -1,6 +1,213 @@
...
+    "self",
+    "parent",
+];
+
+/// Type keywords that are reserved for class/interface/enum names but CAN be
+/// used as method, function, constant, or property names in PHP.
+const PHP_TYPE_KEYWORDS: &[&str] = &[
+    "bool", "false", "float", "int", "iterable", "mixed", "never", "null", "numeric", "object",
+    "resource", "string", "true", "void",
+];
```
Comment (ptondereau) [inline crates/macros/src/parsing.rs:126]: Looking at https://github.com/php/php-src/blob/0880433e61d3c5c350f73f149ed1086200712177/Zend/zend_compile.c#L202

`resource` and `numeric` are allowed for class name

File: crates/macros/src/enum_.rs [hunk 2]
```diff
@@ -84,7 +86,7 @@ pub fn parser(mut input: ItemEnum) -> Result<TokenStream> {
         cases.push(EnumCase {
             ident: variant.ident.clone(),
```
Comment (ptondereau) [inline crates/macros/src/enum_.rs:93]: I think we should also validate this one

File: crates/macros/src/enum_.rs [hunk 3]
```diff
@@ -84,7 +86,7 @@ pub fn parser(mut input: ItemEnum) -> Result<TokenStream> {
...
             name: variant_attr.rename.rename(
-                variant.ident.to_string(),
+                ident_to_php_name(&variant.ident),
                 php_attr.rename_cases.unwrap_or(RenameRule::Pascal),
```
Comment (ptondereau) [inline crates/macros/src/enum_.rs]: And also validate cases (eg: `case True` doesn't work)

File: crates/macros/src/parsing.rs [hunk 4]
```diff
@@ -1,6 +1,213 @@
...
+    };
+
+    assert!(
+        !is_forbidden,
+        "Cannot use '{}' as a PHP {} name: '{}' is a reserved keyword in PHP. \
+         Consider using a different name or the #[php(name = \"...\")] attribute to specify an alternative PHP name.",
+        name,
+        context.description(),
+        name
+    );
```
Comment (ptondereau) [inline crates/macros/src/parsing.rs]: we should use syn:Error handling for macro usage

**Comment by kakserpom** [comment]
@ptondereau please take a look again

**Review by ptondereau — APPROVED** [review]
