### PR TITLE
fix(zend_bailout): Fix zend_bailout handling #537

### LINKED ISSUE #537: PHP bypass Rust destructors when `zend_bailout`
### Description
From discord discussion:

> _emalloc will call zend_bailout should PHP's memory limit be reached. In the background, this will do a long jump bypassing any Rust destructors (effectively not freeing memory).

> We would simply end up intercepting the bailout (like here: https://gist.github.com/awons/d87db73d1ad5eae1445b9de7e3727c6a) and then panicking. But that panic needs to be caught before it crosses the FFI boundary. And then, in C we would need to again bail to make sure the OOM works as it should.

Long jump located [here](https://github.com/php/php-src/blob/d20f4fca69ce82830f5ca2b8cdf2aa26c4c89909/Zend/zend.c#L1268)

## Steps to Reproduce
https://github.com/ptondereau/php-rust-bailout-repro

### Affected Components

- [x] ext-php-rs
- [ ] macros
- [ ] cli (cargo-php)

### PHP Version

```plain
Every PHP version
```

### `ext-php-rs` Version

every

### Operating System

every

### PR DESCRIPTION
**Pull request by kakserpom**
Fixes #537

### CODE REVIEW

**Comment by ptondereau** [comment]
@kakserpom can you rebase, please? This is the next PR I want to merge.

File: src/embed/mod.rs [hunk 1]
```diff
@@ -161,6 +163,9 @@ impl Embed {
             )
         };
 
+        // Prevent the closure from being dropped here since it was consumed in panic_wrapper
+        std::mem::forget(func);
+
```
Comment (ptondereau) [inline src/embed/mod.rs:168]: I think this is not true that we prevent anything here: `func` is already consumed in `let func = unsafe { std::ptr::read(ctx.cast::<F>()) }; catch_unwind(func);`. But don't trust me on this one, and test it.

File: src/zend/try_catch.rs [hunk 2]
```diff
@@ -76,6 +79,9 @@ fn do_try_catch<R, F: FnMut() -> R + RefUnwindSafe>(func: F, first: bool) -> Res
         }
     };
 
+    // Prevent the closure from being dropped here since it was consumed in panic_wrapper
+    std::mem::forget(func);
```
Comment (ptondereau) [inline src/zend/try_catch.rs:83]: same here

**Review by ptondereau — DISMISSED** [review]

File: src/embed/mod.rs (hunk 1 above)
Comment (kakserpom) [reply src/embed/mod.rs:168]: I've tested it and it's correct as is.

Comment (ptondereau) [reply src/embed/mod.rs:168]: This is weird, as `std::ptr::read` moves the closure out of memory.

Comment (kakserpom) [reply src/embed/mod.rs:168]: forget() is needed to avoid a double-drop.

**Comment by kakserpom** [comment]
@ptondereau A spurious CI failure...

File: src/embed/mod.rs (hunk 1 above)
Comment (ptondereau) [reply src/embed/mod.rs:168]: ok TIL
